# -*- mode: restclient; -*-

#################################
# Manual tests for the REST API #
#################################

:auth-token = Token <my-secret-token>

########
# Auth #
########

# Get a token
POST http://localhost:3000/api/login
Content-Type: application/json
{
  "username": "ada",
  "password": "lovelace"
}

# Get a token
POST http://localhost:3000/api/login
Content-Type: application/json
{
  "username": "berta",
  "password": "lovelace"
}

###############
# Productions #
###############

# Get productions
GET http://localhost:3000/api/productions

# Get one production
GET http://localhost:3000/api/productions?limit=1

# Get a specific production
GET http://localhost:3000/api/productions/31411

# Get a specific production in the form of transit
GET http://localhost:3000/api/productions/31411
Accept: application/transit+json

# Get a specific production
GET http://localhost:3000/api/productions?search=DY33722

# Add a production
POST http://localhost:3000/api/productions
Content-Type: application/json
{
  "title": "Hehe",
  "creator": "Foo",
  "description": "not much",
  "source": "978-3-257-07184-11",
  "language": "de",
  "source_date": "2022-06-16T09:38:03.196Z",
  "source_publisher": "Vargos",
  "library_number": "PNX 8434"
}

# Add a production using transit
POST http://localhost:3000/api/productions
Content-Type: application/transit+json
[
  "^ ",
  "~:description",
  "Der Held muss in die Welt hinaus und Abenteuer erleben, um ein Held zu werden. Und was ist mit der Heldin? Doris Dörrie erzählt von drei Reisen nach San Francisco, Japan und Marokko und davon, als Frau in der Welt unterwegs zu sein. Sich dem Ungewissen, Fremden auszusetzen heisst immer auch, den eigenen Ängsten, Abhängigkeiten, Verlusten ins Auge zu sehen. Und dabei zur Heldin der eigenen Geschichte zu werden.",
  "~:creator",
  "Dörrie, Doris",
  "~:source",
  "978-3-257-07184-9",
  "~:title",
  "Die Heldin reist",
  "~:source_publisher",
  "Diogenes",
  "~:language",
  "de",
  "~:source_date",
  [
    "~#LocalDate",
    "2022-01-01"
  ],
  "~:library_number",
  "PNX 8434"
]

# Delete a production
DELETE http://localhost:3000/api/productions/31411
Authorization: :auth-token

# Get the xml for a production
GET http://localhost:3000/api/productions/31017/xml
Content-Type: application/json

# Set the xml for a production
POST http://localhost:3000/api/productions/31017/xml
Accept: application/json
Content-Type: multipart/form-data

< /home/eglic/Downloads/31515.xml

################################
# Assign the library signature #
################################

# Assign a library signature to a production
# should produce a 204
PATCH http://localhost:3000/api/productions/30111
Accept: application/json
Content-Type: application/json
Authorization: :auth-token
{
 "library_signature": "ds70000"
}

# Assign a library signature to a non-existing production
# should produce a 404
PATCH http://localhost:3000/api/productions/301111111
Accept: application/json
Content-Type: application/json
Authorization: :auth-token
{
 "library_signature": "ds70000"
}

# Assign an invalid library signature to a production
# should produce a 400
PATCH http://localhost:3000/api/productions/30111
Accept: application/json
Content-Type: application/json
Authorization: :auth-token
{
 "library_signature": "haha"
}

# Assign an invalid library signature to a production
# should produce a 400
PATCH http://localhost:3000/api/productions/30111
Accept: application/json
Content-Type: application/json
Authorization: :auth-token
{
 "library_signature": "ds123"
}

# Assign an invalid library signature to a production which doesn't have the right state
# should produce a 409
PATCH http://localhost:3000/api/productions/31298
Accept: application/json
Content-Type: application/json
Authorization: :auth-token
{
 "library_signature": "ds12345"
}

####################################
# Marking a production as recorded #
####################################

# Mark a production as recorded
POST http://localhost:3000/api/productions/27707/recorded
Accept: application/json
Content-Type: application/json
Authorization: :auth-token

# Mark a non-existing production as recorded
POST http://localhost:3000/api/productions/1/recorded
Accept: application/json
Content-Type: application/json
Authorization: :auth-token

# Mark production as recorded which doesn't have state 'structured'
POST http://localhost:3000/api/productions/94/recorded
Accept: application/json
Content-Type: application/json
Authorization: :auth-token

#################################
# Marking a production as split #
#################################

# Mark a production as split
POST http://localhost:3000/api/productions/29867/split
Accept: application/json
Content-Type: application/json
Authorization: :auth-token
{
  "volumes": 1,
  "sample-rate": 44100,
  "bit-rate": 48
}

# Mark a non-existing production as split
POST http://localhost:3000/api/productions/1/split
Accept: application/json
Content-Type: application/json
Authorization: :auth-token
{
  "volumes": 1,
  "sample-rate": 44100,
  "bit-rate": 48
}

# Mark production as split with an invalid bit-rate
POST http://localhost:3000/api/productions/300/split
Accept: application/json
Content-Type: application/json
Authorization: :auth-token
{
  "volumes": 1,
  "sample-rate": 44100,
  "bit-rate": 5
}

# Mark production as split with an invalid sample-rate
POST http://localhost:3000/api/productions/300/split
Accept: application/json
Content-Type: application/json
Authorization: :auth-token
{
  "volumes": 1,
  "sample-rate": 44101,
  "bit-rate": 48
}

# Mark production as split which doesn't have state 'pending-split'
POST http://localhost:3000/api/productions/94/split
Accept: application/json
Content-Type: application/json
Authorization: :auth-token
{
  "volumes": 1,
  "sample-rate": 44100,
  "bit-rate": 48
}

##########################
# Repairing a production #
##########################

# Repair a production
POST http://localhost:3000/api/productions/302/repair
Accept: application/json
Authorization: :auth-token

# Repair a production which is not archived
# should produce a 409
POST http://localhost:3000/api/productions/31412/repair
Accept: application/json
Authorization: :auth-token

# Repair a production which doesn't exist
# should produce a 404
POST http://localhost:3000/api/productions/3000000/repair
Accept: application/json
Authorization: :auth-token

##############
# Abacus API #
##############

# Add a production
POST http://localhost:3000/api/abacus/new
Accept: application/json
Content-Type: multipart/form-data; boundary=e82bc39c68f1417d9ea12c5456182f3c

--e82bc39c68f1417d9ea12c5456182f3c
Content-Disposition: form-data; name="file"; filename="SN1_DY99999.xml"
Content-Type: application/xml

<?xml version="1.0" encoding="utf-8"?>
<AbaConnectContainer>
  <Task>
    <Parameter>
      <Application>MadrasApi</Application>
      <Id>Document</Id>
      <Version>1.0</Version>
    </Parameter>
    <Transaction>
      <DocumentData command="mdaDocAdd">
        <artikel_nr>DY99997</artikel_nr>
        <priority>none</priority>
        <deadline>2015-06-29</deadline>
        <title>Test - whout</title>
        <process_status>New</process_status>
        <is_meta>yes</is_meta>
        <mvl_only>no</mvl_only>
        <MetaData>
          <dc>
            <title>Test - whout</title>
            <creator>Test - Gubser, Paul</creator>
            <source>978-3-570-15263-0</source>
            <language>de</language>
            <date>2015-06-29</date>
          </dc>
          <sbs>
            <idVorstufe>DY99997</idVorstufe>
            <printPageNumber>103</printPageNumber>
            <idPrint>0</idPrint>
            <kostenstelle>54120</kostenstelle>
          </sbs>
          <ncc>
            <sourcePublisher>Paul Gubser</sourcePublisher>
            <sourceDate>1967</sourceDate>
            <narrator>N.N.</narrator>
            <setInfo>1</setInfo>
            <revisionDate>2015-06-25</revisionDate>
            <VubisRecordID>378657</VubisRecordID>
          </ncc>
        </MetaData>
      </DocumentData>
    </Transaction>
  </Task>
</AbaConnectContainer>
--e82bc39c68f1417d9ea12c5456182f3c--

# Add a production with faulty xml (missing language)
POST http://localhost:3000/api/abacus/new
Accept: application/json
Content-Type: multipart/form-data; boundary=e82bc39c68f1417d9ea12c5456182f3c

--e82bc39c68f1417d9ea12c5456182f3c
Content-Disposition: form-data; name="file"; filename="SN3_DY15745.xml"
Content-Type: application/xml

<?xml version="1.0" encoding="utf-8"?>
<AbaConnectContainer>
  <Task>
    <Parameter>
      <Application>MadrasApi</Application>
      <Id>Document</Id>
      <Version>1.0</Version>
    </Parameter>
    <Transaction>
      <DocumentData command="mdaDocAdd">
        <artikel_nr>DY99997</artikel_nr>
        <priority>none</priority>
        <deadline>2015-06-29</deadline>
        <title>Test - whout</title>
        <process_status>New</process_status>
        <is_meta>yes</is_meta>
        <mvl_only>no</mvl_only>
        <MetaData>
          <dc>
            <title>Test - whout</title>
            <creator>Test - Gubser, Paul</creator>
            <source>978-3-570-15263-0</source>
            <date>2015-06-29</date>
          </dc>
          <sbs>
            <idVorstufe>DY99997</idVorstufe>
            <printPageNumber>103</printPageNumber>
            <idPrint>0</idPrint>
            <kostenstelle>54120</kostenstelle>
          </sbs>
          <ncc>
            <sourcePublisher>Paul Gubser</sourcePublisher>
            <sourceDate>1967</sourceDate>
            <narrator>N.N.</narrator>
            <setInfo>1</setInfo>
            <revisionDate>2015-06-25</revisionDate>
            <VubisRecordID>378657</VubisRecordID>
          </ncc>
        </MetaData>
      </DocumentData>
    </Transaction>
  </Task>
</AbaConnectContainer>
--e82bc39c68f1417d9ea12c5456182f3c--

# Mark a production as recorded
POST http://localhost:3000/api/abacus/recorded
Accept: application/json
Content-Type: multipart/form-data; boundary=e82bc39c68f1417d9ea12c5456182f3c

--e82bc39c68f1417d9ea12c5456182f3c
Content-Disposition: form-data; name="file"; filename="SN3_DY15745.xml"
Content-Type: application/xml

<?xml version="1.0" encoding="utf-8"?>
<AbaConnectContainer>
  <Task>
    <Parameter>
      <Application>MadrasApi</Application>
      <Id>Document</Id>
      <Version>1.0</Version>
    </Parameter>
    <Transaction>
      <DocumentData command="mdaDocModify">
	<artikel_nr>DY15745</artikel_nr>
	<identifier>dam15388</identifier>
	<priority>none</priority>
	<deadline>2014-03-03</deadline>
	<title>Die lustigen Jungs von Atzavara</title>
	<old_process_status>Structured</old_process_status>
	<process_status>Recorded</process_status>
	<MetaData>
          <dc>
            <title>Die lustigen Jungs von Atzavara</title>
            <creator>Vázquez Montalbán, Manuel</creator>
            <source>3-8031-2356-9</source>
            <language>de</language>
            <identifier>dam15388</identifier>
            <date>2014-03-07</date>
          </dc>
          <sbs>
            <printPageNumber>316</printPageNumber>
            <idMaster>dam15388</idMaster>
            <idPrint>0</idPrint>
            <kostenstelle>54130</kostenstelle>
          </sbs>
          <ncc>
            <sourcePublisher>Wagenbach</sourcePublisher>
            <sourceDate>2002</sourceDate>
            <narrator>Madrid, Venus</narrator>
            <narrator>Störmer, Cathrin</narrator>
            <narrator>Hitz, Heiner</narrator>
            <narrator>Schätzle, Claudia</narrator>
            <narrator>Steccanella, Manuel</narrator>
            <setInfo>1</setInfo>
            <revisionDate>2014-03-03</revisionDate>
          </ncc>
	</MetaData>
      </DocumentData>
    </Transaction>
  </Task>
</AbaConnectContainer>
--e82bc39c68f1417d9ea12c5456182f3c--

# Request the status of a production
POST http://localhost:3000/api/abacus/status
Accept: application/json
Content-Type: multipart/form-data; boundary=e82bc39c68f1417d9ea12c5456182f3c

--e82bc39c68f1417d9ea12c5456182f3c
Content-Disposition: form-data; name="file"; filename="SNStatus_DY90001.xml"
Content-Type: application/xml

<?xml version="1.0" encoding="utf-8"?>
<AbaConnectContainer>
  <Task>
    <Parameter>
      <Application>MadrasApi</Application>
      <Id>Document</Id>
      <Version>1.0</Version>
    </Parameter>
    <Transaction>
      <DocumentData command="mdaDocModify">
        <artikel_nr>DY11817</artikel_nr>
        <identifier>dam20006</identifier>
      </DocumentData>
    </Transaction>
  </Task>
</AbaConnectContainer>
--e82bc39c68f1417d9ea12c5456182f3c--

# Request the status of a (non-existing) production
POST http://localhost:3000/api/abacus/status
Accept: application/json
Content-Type: multipart/form-data; boundary=e82bc39c68f1417d9ea12c5456182f3c

--e82bc39c68f1417d9ea12c5456182f3c
Content-Disposition: form-data; name="file"; filename="SNStatus_DY90001.xml"
Content-Type: application/xml

<?xml version="1.0" encoding="utf-8"?>
<AbaConnectContainer>
  <Task>
    <Parameter>
      <Application>MadrasApi</Application>
      <Id>Document</Id>
      <Version>1.0</Version>
    </Parameter>
    <Transaction>
      <DocumentData command="mdaDocModify">
        <artikel_nr>DY90001</artikel_nr>
        <identifier>dam20006</identifier>
      </DocumentData>
    </Transaction>
  </Task>
</AbaConnectContainer>
--e82bc39c68f1417d9ea12c5456182f3c--

# Update the metadata of a production
POST http://localhost:3000/api/abacus/metadata
Accept: application/json
Content-Type: multipart/form-data; boundary=e82bc39c68f1417d9ea12c5456182f3c

--e82bc39c68f1417d9ea12c5456182f3c
Content-Disposition: form-data; name="file"; filename="SNMeta_DY10339.xml"
Content-Type: application/xml

<?xml version="1.0" encoding="utf-8"?>
<AbaConnectContainer>
  <Task>
    <Parameter>
      <Application>MadrasApi</Application>
      <Id>Document</Id>
      <Version>1.0</Version>
    </Parameter>
    <Transaction>
      <DocumentData command="mdaDocModify">
        <artikel_nr>DY11817</artikel_nr>
        <identifier>dam15562</identifier>
        <title>Die Löwenbraut</title>
        <MetaData>
          <dc>
            <title>Die Löwenbraut</title>
            <creator>Treichler, Hans Peter</creator>
            <source>978-3-85823-796-5</source>
            <language>de</language>
            <identifier>dam15562</identifier>
            <date>2008-07-08</date>
          </dc>
          <sbs>
            <idVorstufe>DY10339</idVorstufe>
            <printPageNumber>336</printPageNumber>
            <idMaster>dam15562</idMaster>
            <idPrint>0</idPrint>
            <kostenstelle>54120</kostenstelle>
            <jahr>1999</jahr>
          </sbs>
          <ncc>
            <sourcePublisher>Neue Zürcher Zeitung</sourcePublisher>
            <sourceDate>1999</sourceDate>
            <narrator>Treichler, Hans Peter</narrator>
            <setInfo>1</setInfo>
            <revisionDate>2015-04-15</revisionDate>
          </ncc>
        </MetaData>
      </DocumentData>
    </Transaction>
  </Task>
</AbaConnectContainer>
--e82bc39c68f1417d9ea12c5456182f3c--

# Update the metadata of a (non-existing) production
POST http://localhost:3000/api/abacus/metadata
Accept: application/json
Content-Type: multipart/form-data; boundary=e82bc39c68f1417d9ea12c5456182f3c

--e82bc39c68f1417d9ea12c5456182f3c
Content-Disposition: form-data; name="file"; filename="SNMeta_DY10339.xml"
Content-Type: application/xml

<?xml version="1.0" encoding="utf-8"?>
<AbaConnectContainer>
  <Task>
    <Parameter>
      <Application>MadrasApi</Application>
      <Id>Document</Id>
      <Version>1.0</Version>
    </Parameter>
    <Transaction>
      <DocumentData command="mdaDocModify">
        <artikel_nr>DY90001</artikel_nr>
        <identifier>dam15562</identifier>
        <title>Die Löwenbraut</title>
        <MetaData>
          <dc>
            <title>Die Löwenbraut</title>
            <creator>Treichler, Hans Peter</creator>
            <source>978-3-85823-796-5</source>
            <language>de</language>
            <identifier>dam15562</identifier>
            <date>2008-07-08</date>
          </dc>
          <sbs>
            <idVorstufe>DY10339</idVorstufe>
            <printPageNumber>336</printPageNumber>
            <idMaster>dam15562</idMaster>
            <idPrint>0</idPrint>
            <kostenstelle>54120</kostenstelle>
            <jahr>1999</jahr>
          </sbs>
          <ncc>
            <sourcePublisher>Alte Zürcher Zeitung</sourcePublisher>
            <sourceDate>1999</sourceDate>
            <narrator>Treichler, Hans Peter</narrator>
            <setInfo>1</setInfo>
            <revisionDate>2015-04-15</revisionDate>
          </ncc>
        </MetaData>
      </DocumentData>
    </Transaction>
  </Task>
</AbaConnectContainer>
--e82bc39c68f1417d9ea12c5456182f3c--

# Metrics
GET http://localhost:3000/metrics
