* mdr2

A Production Management Tool for [[http://www.daisy.org/daisypedia/daisy-digital-talking-book][DAISY Talking Books]].

[[https://versions.deps.co/sbsdev/mdr2][https://versions.deps.co/sbsdev/mdr2/status.svg]]

** Installation
Build with [[https://github.com/technomancy/leiningen][Leiningen]] using the [[https://github.com/immutant/lein-immutant][lein immutant plugin]].

#+BEGIN_SRC shell
lein immutant war --nrepl-start --nrepl-port 42278
#+END_SRC

Deploy the resulting war file in [[http://wildfly.org/][Wildfly]].

** Documentation

- [[https://github.com/sbsdev/mdr2/wiki][Wiki]]
- [[https://sbsdev.github.io/mdr2][API Docs]]

At its core mdr2 integrates a number of systems and coordinates the
production of DAISY Talking Books from inception through to archiving.

The involved systems are:

- ABACUS ::  Order management and initiation of productions is
             typically done in the ERP namely ABACUS.
- Library ::  Some production orders come directly from the library as
              they are not managed in the ERP.
- Obi :: The actual recording of the production is done in [[http://www.daisy.org/project/obi][Obi]].
- DAISY Pipeline :: The recorded productions are validated and
                    converted to DAISY Talking Books using software
                    from both the [[http://www.daisy.org/project/pipeline][DAISY Pipeline 1]] and [[http://www.daisy.org/pipeline2][DAISY Pipeline
                    2]] projects
- Archive :: Once all the artifacts have been created they are
             archived in a legacy in-house archive.

** Configuration and Dependencies
Configuration is fairly complex and involves a lot of dependencies. It
is recommended to use the [[https://github.com/sbsdev/sbs-infrastructure/blob/master/madras2.yml][ansible installation script]] which automates
the whole process.

Amongst other you will need [[http://wildfly.org/][Wildfly]], [[http://www.daisy.org/project/pipeline][DAISY Pipeline 1]], [[http://www.daisy.org/pipeline2][DAISY Pipeline
2]], [[https://wiki.debian.org/genisoimage][mkisofs]], etc.

** License

Copyright © 2014, 2015 Swiss Library for the Blind, Visually Impaired and Print Disabled.

Distributed under the [[http://www.gnu.org/licenses/agpl-3.0.html][GNU Affero General Public License]]. See the file LICENSE.
