on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - '[0-9].[0-9]+.[0-9]+' # Push events to matching release tags, i.e. 0.8.4

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install npm dependecies
        run: npm install
      - name: Build project 
        run: lein uberjar
      - name: Create release and upload release asset
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          files: ./target/uberjar/mdr2.jar

